# Generated by Django 5.1.5 on 2025-02-25 20:35

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=90, null=True)),
                ('city', models.CharField(max_length=7, null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('administrative_unit', models.CharField(max_length=50, null=True)),
                ('flat_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
                ('nip', models.IntegerField()),
                ('krs', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('org_status', models.SmallIntegerField(default=0)),
                ('rendered', models.BooleanField(default=False)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=60)),
                ('login', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=20)),
                ('accesslevel', models.SmallIntegerField(default=0)),
                ('first_login_ip', models.CharField(max_length=15)),
                ('last_login_ip', models.CharField(max_length=15)),
                ('created_at', models.CharField(max_length=12)),
                ('deleted_at', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='organisation_needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('sum_value', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('currency', models.CharField(max_length=3)),
                ('is_closed', models.BooleanField(default=False)),
                ('organisation_relised_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relised_org_id', to='mergeservice.organisations')),
                ('organisations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ_id', to='mergeservice.organisations')),
            ],
        ),
        migrations.CreateModel(
            name='grants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('sum_value', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateField()),
                ('closed_at', models.DateField(null=True)),
                ('organisations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_id', to='mergeservice.organisations')),
                ('receiver_organisation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations_id', to='mergeservice.organisations')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=90, null=True)),
                ('city', models.CharField(max_length=7)),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('administrative_unit', models.CharField(max_length=30, null=True)),
                ('build_number', models.CharField(max_length=10, null=True)),
                ('flat_number', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
                ('birth_date', models.DateField(null=True)),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mergeservice.users')),
            ],
        ),
        migrations.AddField(
            model_name='organisations',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mergeservice.users'),
        ),
        migrations.CreateModel(
            name='organisation_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_level_in_organisation', models.SmallIntegerField(default=0)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mergeservice.organisations')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mergeservice.users')),
            ],
        ),
        migrations.CreateModel(
            name='join_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mergeservice.organisations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mergeservice.users')),
            ],
        ),
    ]
